### ISSUE TITLE
WG Template for the comparison of RJDemetra and RJDemetra3 - Bug fix

### ISSUE THREAD

**Issue by maria-novas** [palatej/rjdemetra3#1]
Dear Jean,
I send you attached a Workspace with the Industrial Producion Index series.  Something might happen when there is not canonical decomposition. This is the result obtained when I run the template to compare 2.2 version vs 3.0, with METHOD <- "TS" and SPEC <- “RSAfull", and also with SPEC <- “RSA5". 
[IPI.zip](https://github.com/palatej/rjdemetra3/files/6155932/IPI.zip)

Thanks in advance

> source("jd_calculation.R")                        # Calculation of the versions comparison
  Show Traceback
 
 Rerun with Debug
 
Error in .jcall("demetra/tramoseats/r/TramoSeats", "Ldemetra/tramoseats/r/TramoSeats$Results;",  : 
  demetra.seats.SeatsException: Invalid decomposition
 
> source("latex_compilation.R")                     # Compilation of LaTeX and PDF file
Error in paste0("\\hline\n\\endhead\n", "\\hline\n", "\\multicolumn{",  : 
  object 'tab1' not found

**Comment by palatej** [comment]
OK. I see the problem.
Many thanks
