### ISSUE TITLE
Problems with installing rjd3toolkit

### ISSUE THREAD

**Issue by merangelik** [palatej/rjdemetra3#11]
`remotes::install_github("palatej/rjd3toolkit")`

We get the following error message:

`Error: package or namespace load failed for ‘rjd3toolkit’:
 .onLoad failed in loadNamespace() for 'rjd3toolkit', details:
  call: fun(libname, pkgname)
  error: Your java version is 1.8.0_362.  N or higher.
Error: loading failed
Execution halted`

However when I retrieve the Java version from our system I get the following response:
`java -version
openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment (build 17.0.7+7-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 17.0.7+7-Ubuntu-0ubuntu120.04, mixed mode, sharing)`

Since your prerequisites are the following, I think there might be an issue with the installation code: 

RJDemetra3 relies on the [rJava](https://cran.r-project.org/package=rJava) package and Java SE 17 or later version is required.

**Comment by AQLT** [comment]
The version used by default by your system can be different by the one used by default by R. In your case R used the version 1.8. You can for example test it using the following command:
```r
library(rJava)
.jinit()
.jcall("java/lang/System", "S", "getProperty", "java.runtime.version")
```
In ubuntu the following installation should work
```
RUN apt-get update --yes && \
    apt-get install --yes libprotoc-dev libprotobuf-dev protobuf-compiler openjdk-17-jdk && \
    R CMD javareconf
```
My advice would be to run `R CMD javareconf` and/or to change the JAVA_HOME Path and to test which version is used by R with
```r
library(rJava)
.jinit()
.jcall("java/lang/System", "S", "getProperty", "java.runtime.version")
```
